In [33]:
import numpy as np
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import classification_report
import warnings
warnings.filterwarnings("ignore")

In [34]:
# Step 1: Create an imbalanced binary classification dataset
X, y  = make_classification(n_samples=1000, n_features=10, n_informative=2, n_redundant=8,
                            weights=[0.9, 0.1], flip_y=0, random_state=42)

np.unique(y, return_counts=True)

(array([0, 1]), array([900, 100], dtype=int64))

In [35]:
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, stratify=y, random_state=42)

## Experiment 1: Train Logistic Regression Classifier

In [36]:
log_reg = LogisticRegression(C=1, solver='liblinear')
log_reg.fit(X_train, y_train)
y_pred_log_reg = log_reg.predict(X_test)
print(classification_report(y_test, y_pred_log_reg))

              precision    recall  f1-score   support

           0       0.95      0.96      0.95       270
           1       0.60      0.50      0.55        30

    accuracy                           0.92       300
   macro avg       0.77      0.73      0.75       300
weighted avg       0.91      0.92      0.91       300



## Experiment 2: Train Random Forest Classifier

In [37]:
rf_clf = RandomForestClassifier(n_estimators= 30, max_depth=3)
rf_clf.fit(X_train, y_train)
y_pred_rf  = rf_clf.predict(X_test)
print(classification_report(y_test, y_pred_rf))

              precision    recall  f1-score   support

           0       0.97      1.00      0.98       270
           1       0.95      0.70      0.81        30

    accuracy                           0.97       300
   macro avg       0.96      0.85      0.89       300
weighted avg       0.97      0.97      0.96       300



## Experiment 3: Train XGBoost

In [38]:
xgb_clf = XGBClassifier(use_label_encoder = False, eval_metric = 'logloss')
xgb_clf.fit(X_train, y_train)
y_pred_xgb = xgb_clf.predict(X_test)
print(classification_report(y_test, y_pred_xgb))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       270
           1       0.96      0.80      0.87        30

    accuracy                           0.98       300
   macro avg       0.97      0.90      0.93       300
weighted avg       0.98      0.98      0.98       300



## Experiment 4: handle Class imbalance using  SMOTETomek and then Train XGBoost

In [39]:
from imblearn.combine import SMOTETomek

smt = SMOTETomek(random_state=42)
X_train_res, y_train_res = smt.fit_resample(X_train, y_train)

np.unique(y_train_res, return_counts=True)

(array([0, 1]), array([619, 619], dtype=int64))

In [40]:
xgb_clf = XGBClassifier(use_label_encoder = False, eval_metric='logloss')
xgb_clf.fit(X_train_res, y_train_res)
y_pred_xgb = xgb_clf.predict(X_test)
print(classification_report(y_test, y_pred_xgb))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98       270
           1       0.81      0.83      0.82        30

    accuracy                           0.96       300
   macro avg       0.89      0.91      0.90       300
weighted avg       0.96      0.96      0.96       300



## <font color=blue>Track Experiments Using MLFlow</font>

In [41]:
# list_of_params = [
#     {'C':1, 'solver':'liblinear'},
#     {'n_estimators':30,'max_depth':3},
#     {'use_label_encoder': False, 'eval_metric' : 'logloss'},
#     {'use_label_encoder': False, 'eval_metric' : 'logloss'}
# ]

models = [
    (
        "Logistic Regression",
        {'C':1, 'solver':'liblinear'},
        LogisticRegression(),
        (X_train,y_train),
        (X_test, y_test)
    ),
    (
        "Random Forest",
        {'n_estimators':30,'max_depth':3},
        RandomForestClassifier(),
        (X_train, y_train),
        (X_test, y_test)
    ),
    (
        "XGBClassifier",
        {'use_label_encoder': False, 'eval_metric' : 'logloss'},
        XGBClassifier(),
        (X_train, y_train),
        (X_test, y_test)
    ),
    (
        "XGBClassifier with SMOTE",
        {'use_label_encoder': False, 'eval_metric' : 'logloss'},
        XGBClassifier(),
        (X_train_res, y_train_res),
        (X_test, y_test)
    )
]

In [42]:
reports = []

for model_name,params, model, train_set, test_set in models:
    X_train = train_set[0]
    y_train = train_set[1]
    X_test = test_set[0]
    y_test = test_set[1]
    
    model.set_params(**params)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    report = classification_report(y_test, y_pred, output_dict=True)
    reports.append(report)

In [43]:
reports

[{'0': {'precision': 0.9454545454545454,
   'recall': 0.9629629629629629,
   'f1-score': 0.9541284403669725,
   'support': 270.0},
  '1': {'precision': 0.6,
   'recall': 0.5,
   'f1-score': 0.5454545454545454,
   'support': 30.0},
  'accuracy': 0.9166666666666666,
  'macro avg': {'precision': 0.7727272727272727,
   'recall': 0.7314814814814814,
   'f1-score': 0.749791492910759,
   'support': 300.0},
  'weighted avg': {'precision': 0.9109090909090909,
   'recall': 0.9166666666666666,
   'f1-score': 0.91326105087573,
   'support': 300.0}},
 {'0': {'precision': 0.9607142857142857,
   'recall': 0.9962962962962963,
   'f1-score': 0.9781818181818182,
   'support': 270.0},
  '1': {'precision': 0.95,
   'recall': 0.6333333333333333,
   'f1-score': 0.76,
   'support': 30.0},
  'accuracy': 0.96,
  'macro avg': {'precision': 0.9553571428571428,
   'recall': 0.8148148148148149,
   'f1-score': 0.8690909090909091,
   'support': 300.0},
  'weighted avg': {'precision': 0.9596428571428572,
   'recall':

In [44]:
import mlflow

In [45]:
mlflow.set_experiment("Anamoly Detection 2")
mlflow.set_tracking_uri("http://127.0.0.1:5000/")


for i, element in enumerate(models):
    model_name = element[0]
    params = element[1]
    model = element[2]
    report = reports[i]
    
    
    with mlflow.start_run(run_name = model_name):
        mlflow.log_params(params)
        # mlflow.log_metric('accuracy', report['accuracy'])
        # mlflow.log_metric('recall_class_1', report['1']['recall'])
        # mlflow.log_metric('recall_class_0', report['0']['recall'])
        # mlflow.log_metric('f1_score_macro', report['macro avg']['f1-score'])
        
        mlflow.log_metrics({
            'accuracy': report['accuracy'],
            'recall_class_1': report['1']['recall'],
            'recall_class_0': report['0']['recall'],
            'f1_score_macro': report['macro avg']['f1-score'] 
        })
        
        
        if "XGB" in model_name:
            mlflow.xgboost.log_model(model, "model")
        else:
            mlflow.sklearn.log_model(model, "model")

2024/08/16 11:01:16 WARNING mlflow.models.model: Input example should be provided to infer model signature if the model signature is not provided when logging the model.
2024/08/16 11:01:16 INFO mlflow.tracking._tracking_service.client: 🏃 View run Logistic Regression at: http://127.0.0.1:5000/#/experiments/196952936197526188/runs/261fc378e1f642f1848fa7421deeebed.
2024/08/16 11:01:16 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/196952936197526188.
2024/08/16 11:01:20 WARNING mlflow.models.model: Input example should be provided to infer model signature if the model signature is not provided when logging the model.
2024/08/16 11:01:20 INFO mlflow.tracking._tracking_service.client: 🏃 View run Random Forest at: http://127.0.0.1:5000/#/experiments/196952936197526188/runs/152ae624c50948ef9c990c6891e94e31.
2024/08/16 11:01:20 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1969

### Register the model

In [46]:
model_name = "XGB-Smote"
run_id = input("Enter Run ID:")
model_uri = f"runs:/{run_id}/model"
result = mlflow.register_model(model_uri, model_name)

Registered model 'XGB-Smote' already exists. Creating a new version of this model...
2024/08/16 11:02:03 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: XGB-Smote, version 3
Created version '3' of model 'XGB-Smote'.


### Load the model

In [26]:
model_name = "XGB-Smote"
model_version = 2
model_uri = f"models:/{model_name}/{model_version}"

loaded_model = mlflow.xgboost.load_model(model_uri)
y_pred_xgb = loaded_model.predict(X_test)
y_pred_xgb[:4]

array([0, 0, 0, 0])

In [51]:
model_name = "XGB-Smote"
model_aliases = '@challenger'
model_uri = f"models:/{model_name}{model_aliases}"

loaded_model = mlflow.xgboost.load_model(model_uri)
y_pred_xgb = loaded_model.predict(X_test)
y_pred_xgb[:4]

array([0, 0, 0, 0])

In [52]:
dev_model_uri = f"models:/{model_name}{model_aliases}"
prod_model = 'anomaly-detection-prod'

client = mlflow.MlflowClient()
client.copy_model_version(src_model_uri=dev_model_uri, dst_name=prod_model)

Successfully registered model 'anomaly-detection-prod'.
Copied version '3' of model 'XGB-Smote' to version '1' of model 'anomaly-detection-prod'.


<ModelVersion: aliases=[], creation_timestamp=1723786889380, current_stage='None', description='this is trained on anomaly detection data and with Smote technique', last_updated_timestamp=1723786889380, name='anomaly-detection-prod', run_id='847513b692354899a2554e9568914e47', run_link='', source='models:/XGB-Smote/3', status='READY', status_message='', tags={}, user_id='', version='1'>

### Load the prod model

In [53]:
model_uri = f"models:/{prod_model}@champion"

loaded_model = mlflow.xgboost.load_model(model_uri)
y_pred_xgb = loaded_model.predict(X_test)
y_pred_xgb[:4]

array([0, 0, 0, 0])